# Generated by Django 4.2.11 on 2024-12-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EK_APP', '0002_ekpjlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_th', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('qr_code', models.IntegerField(max_length=8)),
                ('age', models.IntegerField(max_length=3)),
            ],
        ),
    ]
