# Generated by Django 4.2.11 on 2024-12-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EK_APP', '0003_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='qr_code',
            field=models.IntegerField(),
        ),
    ]
