# Generated by Django 4.2.11 on 2024-12-07 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EK_APP', '0004_alter_driver_age_alter_driver_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='nationality',
        ),
    ]
