# Generated by Django 4.2.11 on 2024-12-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EK_APP', '0006_alter_driver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='driver_images/'),
        ),
    ]
