# Generated by Django 4.2.11 on 2024-12-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EK_APP', '0007_driver_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Driver', 'verbose_name_plural': 'Drivers'},
        ),
        migrations.AlterModelOptions(
            name='ekpj',
            options={'verbose_name': 'EKPJ User', 'verbose_name_plural': 'EKPJ Users'},
        ),
        migrations.AlterModelOptions(
            name='ekpjlogin',
            options={'verbose_name': 'EKPJ Login', 'verbose_name_plural': 'EKPJ Logins'},
        ),
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ekpj',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
