# Generated by Django 4.2.11 on 2024-12-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EK_APP', '0008_alter_driver_options_alter_ekpj_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ekpj',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ekpjlogin',
            options={},
        ),
        migrations.AlterField(
            model_name='ekpj',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
