# Generated by Django 4.2.11 on 2024-12-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EK_APP', '0009_alter_driver_options_alter_ekpj_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
