# Generated by Django 5.1.4 on 2024-12-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EK_APP', '0010_alter_driver_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('round_id', models.IntegerField(primary_key=True, serialize=False)),
                ('round_name', models.CharField(max_length=255)),
                ('round_date', models.DateField()),
                ('round_base_weight', models.IntegerField()),
                ('round_max_weight', models.IntegerField()),
                ('round_changes', models.IntegerField()),
                ('round_pit_lane', models.IntegerField()),
                ('champion_id', models.IntegerField()),
                ('track_id', models.IntegerField()),
                ('race_status', models.IntegerField()),
                ('durition_min', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
