# Generated by Django 5.1.4 on 2024-12-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EK_APP', '0013_alter_driver_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='qr_code',
            field=models.IntegerField(max_length=255),
        ),
    ]
