# Generated by Django 4.2.7 on 2024-12-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_id', models.CharField(max_length=100)),
                ('championship_name', models.CharField(max_length=100)),
                ('round_name', models.CharField(max_length=100)),
                ('round_date', models.CharField(max_length=100)),
                ('race_status', models.CharField(max_length=100)),
                ('driver_changes', models.CharField(max_length=100)),
                ('track', models.CharField(max_length=100)),
                ('base_weight', models.CharField(max_length=100)),
                ('max_weight', models.CharField(max_length=100)),
                ('race_duration_time', models.CharField(max_length=100)),
                ('pitlane', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team_in_round',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('championship', models.CharField(max_length=100)),
                ('round', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('team_number', models.CharField(max_length=100)),
                ('start_position', models.CharField(max_length=100)),
                ('finish_position', models.CharField(max_length=100)),
                ('position_points', models.CharField(max_length=100)),
                ('penalty_points', models.CharField(max_length=100)),
                ('total_points', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team_numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number_id', models.CharField(max_length=100)),
                ('championship_id', models.CharField(max_length=100)),
                ('team_id', models.CharField(max_length=100)),
                ('team_number', models.CharField(max_length=100)),
            ],
        ),
    ]
